image: node:12.10

services:
  - postgres:12
  - redis:5

variables:
  POSTGRES_DB: lost_grandma_test
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install

test:
  stage: test
  script:
    - npm test

